name: "pull_request"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: build
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: --full-stacktrace build

      - name: Upload reports
        uses: actions/upload-artifact@v3.1.0
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Stop Gradle daemons
        run: ./gradlew --stop

  ktlint:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Format
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: ktlintFormat

      - name: Stop Gradle daemons
        run: ./gradlew --stop

      - name: "Commit formatted files"
        uses: stefanzweifel/git-auto-commit-action@v4.15.0
        with:
          commit_message: Format files using ktlint
          file_pattern: "**/*.kt"

  update-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Checkout
        run: rm -rf docs

      - name: Format
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: :mutable-utils:dokkaHtml

      - name: Stop Gradle daemons
        run: ./gradlew --stop

      - name: "Commit formatted files"
        uses: stefanzweifel/git-auto-commit-action@v4.15.0
        with:
          commit_message: Update documentation
          file_pattern: "docs/*"
